; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; Supported only on targets that don't have native misaligned access
; REQUIRES: mips-registered-target
; RUN: opt -mtriple mips < %s -memcpyopt -S -enable-memcpyopt-memoryssa=0 | FileCheck %s
; RUN: opt -mtriple mips < %s -memcpyopt -S -enable-memcpyopt-memoryssa=1 -verify-memoryssa | FileCheck %s

target datalayout = "e-m:e-i64:64-i128:128-n32:64-S128"

define void @foo(i64* nocapture %P) {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast i64* [[P:%.*]] to i16*
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, i16* [[TMP0]], i64 1
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i16* [[ARRAYIDX]] to i32*
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i16, i16* [[TMP0]], i64 3
; CHECK-NEXT:    store i16 0, i16* [[TMP0]], align 2
; CHECK-NEXT:    store i32 0, i32* [[TMP1]], align 4
; CHECK-NEXT:    store i16 0, i16* [[ARRAYIDX1]], align 2
; CHECK-NEXT:    ret void
;
entry:
  %0 = bitcast i64* %P to i16*
  %arrayidx = getelementptr inbounds i16, i16* %0, i64 1
  %1 = bitcast i16* %arrayidx to i32*
  %arrayidx1 = getelementptr inbounds i16, i16* %0, i64 3
  store i16 0, i16* %0, align 2
  store i32 0, i32* %1, align 4
  store i16 0, i16* %arrayidx1, align 2
  ret void
}

