; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mattr=+pcrel -enable-misched=false -mtriple=nanomips-unknown=elf -verify-machineinstrs < %s | FileCheck %s

@b = external dso_local local_unnamed_addr global [0 x i32], align 4

define dso_local void @foo(i32* nocapture readonly %a) local_unnamed_addr {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiu $a[[REG1:[0-9]+]], $a0, 40000
; CHECK-DAG:     lw $a0, 0($a[[REG1]])
; CHECK-DAG:     lw $a1, 4($a[[REG1]])
; CHECK-NEXT:    bc sink
entry:
  %arrayidx = getelementptr inbounds i32, i32* %a, i32 10000
  %0 = load i32, i32* %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds i32, i32* %a, i32 10001
  %1 = load i32, i32* %arrayidx1, align 4
  tail call void @sink(i32 signext %0, i32 signext %1) #3
  ret void
}

declare dso_local void @sink(i32 signext, i32 signext) local_unnamed_addr

define dso_local void @bar() local_unnamed_addr {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lapc.b $a[[REG2:[0-9]+]], b+40000
; CHECK-DAG:     lw $a0, 0($a[[REG2]])
; CHECK-DAG:     lw $a1, 4($a[[REG2]])
; CHECK-NEXT:    bc sink
entry:
  %0 = load i32, i32* getelementptr inbounds ([0 x i32], [0 x i32]* @b, i32 0, i32 10000), align 4
  %1 = load i32, i32* getelementptr inbounds ([0 x i32], [0 x i32]* @b, i32 0, i32 10001), align 4
  tail call void @sink(i32 signext %0, i32 signext %1)
  ret void
}

define dso_local i32 @frob(i32* nocapture readonly %a) local_unnamed_addr {
; CHECK-LABEL: frob:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiu $a1, $a0, 40000
; CHECK-NEXT:    lw $a1, 0($a1)
; CHECK-NEXT:    addiu $a0, $a0, 16380
; CHECK-NEXT:    lw $a0, 0($a0)
; CHECK-NEXT:    addu $a0, $a0, $a1
; CHECK-NEXT:    jrc $ra
entry:
  %arrayidx = getelementptr inbounds i32, i32* %a, i32 10000
  %0 = load i32, i32* %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds i32, i32* %a, i32 4095
  %1 = load i32, i32* %arrayidx1, align 4
  %add = add nsw i32 %1, %0
  ret i32 %add
}
