; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=nanomips-unknown=elf -O2 -mno-check-zero-division -verify-machineinstrs < %s | FileCheck %s

define dso_local i32 @foo(i32 signext %a) local_unnamed_addr {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li $a1, 0x3e0f83e1
; CHECK-NEXT:    muh $a0, $a0, $a1
; CHECK-NEXT:    srl $a1, $a0, 31
; CHECK-NEXT:    sra $a0, $a0, 5
; CHECK-NEXT:    addu $a0, $a0, $a1
; CHECK-NEXT:    jrc $ra
entry:
  %div = sdiv i32 %a, 132
  ret i32 %div
}

define dso_local i32 @bar(i32 signext %a) local_unnamed_addr #0 {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li $a1, 132
; CHECK-NEXT:    div $a0, $a0, $a1
; CHECK-NEXT:    jrc $ra
entry:
  %div = sdiv i32 %a, 132
  ret i32 %div
}

attributes #0 = { optsize }

