; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=nanomips-unknown=elf --frame-pointer=none -verify-machineinstrs < %s | FileCheck %s

define dso_local void @foo() local_unnamed_addr {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    save 4080, $s0, $s1, $s2
; CHECK-NEXT:    .cfi_def_cfa_offset 4080
; CHECK-NEXT:    .cfi_offset 16, -4
; CHECK-NEXT:    .cfi_offset 17, -8
; CHECK-NEXT:    .cfi_offset 18, -12
; CHECK-NEXT:    addiu $sp, $sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 4112
; CHECK-NEXT:	 addiu $a0, $sp, 4
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    addiu $sp, $sp, 32
; CHECK-NEXT:    restore.jrc 4080, $s0, $s1, $s2
entry:
  %__tmp = alloca [4096 x i8], align 1
  %0 = getelementptr inbounds [4096 x i8], [4096 x i8]* %__tmp, i32 0, i32 0
  call void asm sideeffect "", "*m,~{$16},~{$17},~{$18},~{$1}"(ptr nonnull elementtype([4096 x i8]) %__tmp)
  ret void
}
