name: Sync upstream tags

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Fork
              uses: actions/checkout@v4
              with:
                fetch_depth: 0

            - name: Sync tags
              run:
                git remote add upstream https://github.com/llvm/llvm-project
                git fetch --tags upstream
                git push origin --tags
